
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Financial_Management_Application.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Notification
{

    public long Id { get; set; }

    public long AddressId { get; set; }

    public string Email { get; set; }

    public long DivisionId { get; set; }

    public string notifyType { get; set; }

    public string notifyText { get; set; }

    public System.DateTime timeStamp { get; set; }



    public virtual Address Address { get; set; }

    public virtual Division Division { get; set; }

}

}
