
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Financial_Management_Application.Models
{

using System;
    using System.Collections.Generic;
    
public partial class NotRestricted
{

    public long Id { get; set; }

    public string name { get; set; }

    public long Role { get; set; }

    public long Division { get; set; }



    public virtual Division Division1 { get; set; }

    public virtual Role Role1 { get; set; }

}

}
