//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Financial_Management_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionRequest
    {
        public long Id { get; set; }
        public Nullable<long> requestedForUserId { get; set; }
        public long productId { get; set; }
        public int quantity { get; set; }
        public long cartId { get; set; }
        public decimal unitPrice { get; set; }
    
        public virtual User User { get; set; }
    }
}
